version: '2.3'
services:
    db:
        image: mysql:5.6
        container_name: mybarberdb
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: mybarberdb
        ports:
            - "3306:3306"
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

    api:
       image: mybarber/api:latest
       container_name: mybarberapi
       depends_on:
            db:
                condition: service_healthy
       environment: 
            SPRING_PROFILES_ACTIVE: prod
       ports:
            - '8080:8080'

    app:
       image: mybarber/app:latest
       container_name: maybarberapp
       ports:
            - '4200:4200'

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - '9090:9090'
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - api

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - '3000:3000'
        volumes:
            - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
            - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
            - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
        depends_on:
            - prometheus


